def test_failing():
    assert (1, 2, 3) == (3, 2, 1)


def test_failing_again():
    assert 1 in (2, 3, 4)
